dev to master
WollMux/formbox-api pull request #10
Opened 2018-01-24 14:56 UTC by bjoernranft

2018-01-30 13:55 UTC, Eymux requested changes
Mit Ausnahme von ein paar Kleinigkeit finde ich den PR sehr gut.
Aber mir fehlt noch der Switch, um Dateien direkt ohne Konvertierung nach Base64 zu laden.

Und ein paar Unittests würden auch nicht schaden.
Und beheben Sie bitte die Fehler in den Tests.

2018-01-30 13:55 UTC, Eymux commented on src/api/configuration.api.ts
> +  api.get('/fragmentList', asyncHandler(async (req, res, next) => {
Ich bin gegen Großbuchstaben in URLs. Wieso nehmen Sie nicht einfach die Route '/fragmente'?
Wenn es unbedingt eine eigene Route sein muss, dann sollte der Name 'fragment-list' sein.

2018-01-30 13:55 UTC, Eymux commented on config/fragments.json
> +	"Adresse_Angaben": "fragmente/Adresse_Angaben.docx",
Der Inhalt der Configdateien sollte eigentlich nicht im Repo sein.

2018-01-30 13:55 UTC, Eymux commented on config/templates.json
> +{
Der Inhalt der Configdateien sollte eigentlich nicht im Repo sein.

2018-02-05 07:42 UTC, sikelerd commented on config/fragments.json
> +	"Adresse_Angaben": "fragmente/Adresse_Angaben.docx",
Es gibt jetzt bei uns ein Git formbox-standard-config, das für die Konfiguration gedacht ist.

2018-02-06 07:46 UTC, sikelerd requested changes

2018-02-06 07:46 UTC, sikelerd commented on test/services/configuration.service.spec.ts
> +    const testDocxTestFragmentAsBase64String = 'UEsDBBQAAAgAAKRreEtexjIMJwAAACcAAAAIAAAAbWltZXR5cGVhcHBsaWNhdGlvbi92bmQub2FzaXMub3BlbmRvY3VtZW50LnRleHRQSwMEFAAACAAApGt4SwAAAAAAAAAAAAAAABwAAABDb25maWd
Die Konstanten bitte an den Anfang der Datei verschieben

2018-02-06 07:46 UTC, sikelerd commented on test/services/configuration.api.spec.ts
> +var base_url = "https://" + process.env.HOST + ":" + process.env.PORT;
const

2018-02-06 07:46 UTC, sikelerd commented on src/api/status.api.ts
> +import * as express from 'express';
Für was brauchen wir die Status-Api?

2018-02-06 07:46 UTC, sikelerd commented on package.json
> +    "pm2": "^2.9.1",
Dieses Paket wird bisher nicht verwendet

2018-02-06 07:46 UTC, sikelerd commented on src/api/configuration.api.ts
> +        const name = req.params.name;
Ich würde lieber über die Query-Parameter gehen und nicht über den Path. 
also /fragmente?name=test.docx&base64=true anstatt /fragmente/test.docx/true

2018-02-06 07:46 UTC, sikelerd commented on src/api/configuration.api.ts
> +  api.get('/vorlagen/:name/:base64?', asyncHandler(async (req, res, next) => {
Ich würde lieber über die Query-Parameter gehen und nicht über den Path. 
also /fragmente?name=test.docx&base64=true anstatt /fragmente/test.docx/true

2018-02-06 07:46 UTC, sikelerd commented on src/api/configuration.api.ts
> +  api.get('/fragmente', asyncHandler(async (req, res, next) => {
Ist diese Route noch notwendig?

2018-02-06 07:46 UTC, sikelerd commented on src/api/configuration.api.ts
> +  api.get('/vorlagen', asyncHandler(async (req, res, next) => {
Ist diese Route noch notwendig?

2018-02-06 07:46 UTC, sikelerd commented on src/app/app.main.ts
> +  setFSPathes(): void {
Diese Methode wird nicht aufgerufen

2018-02-06 07:46 UTC, sikelerd commented on src/services/configuration.service.ts
> +  async getFragment(name: string): Promise<string> {
Die Methoden zum Zugriff auf die Dateien sollten in einen eigenen Service verschoben werden. Im ConfigurationService würde ich nur die Zugriffe auf die Konfiguration erwarten.

2018-02-07 13:54 UTC, bjoernranft commented on src/api/status.api.ts
> +import * as express from 'express';
..hatte ich als debug ausgabe für client entwickler gedacht um sich alle verfügbaren routen (mit parameter) anzeigen zu lassen.

..klappt leider noch nicht, laut express doku sollte app.routes funktionieren,
auch mit npm 'express-list-routes'-Paket funktioniert es nicht, ich vermute wegen DI. 

liefere ich nach sobald ich eine Lösung habe.

2018-02-08 08:44 UTC, Eymux requested changes
Dokumentation fehlt auch noch.

2018-02-08 08:44 UTC, Eymux commented on Jenkinsfile
> +        DISABLE_SSL = 'true'
Die Variable bitte noch in .env eintragen. Und dann .env in .env.sample umbenennen, damit die nicht aus Versehen produktiv geht.

2018-02-08 08:44 UTC, Eymux commented on src/app/app.main.ts
> +    this.startServer(this.readCertificates());
Gehört da nicht ein 'else' hin?

2018-02-08 09:40 UTC, sikelerd submitted a review, later dismissed

2018-02-08 12:56 UTC, merged