Code Guidelines und Sonar
WollMux/formbox-api pull request #4
Opened 2017-12-05 11:39 UTC by sikelerd

Die Code Guidelines sind an denen von Angular-tslint-rules orientiert. Es gibt ein paar Änderungen die in docs/CONTRIBUTING beschrieben sind. So gut wie alle Punkte aus docs/CONTRIBUTING werden durch die tslint rules überprüft.

2017-12-05 12:06 UTC, Eymux requested changes

2017-12-05 12:06 UTC, Eymux commented on docs/CONTRIBUTING.md
> +* Double Quotes für Strings
Ich dachte wir hatten uns auf Single Quotes geeinigt? Habe ich das falsch verstanden oder gibt es für die Änderung einen Grund?

2017-12-05 12:06 UTC, Eymux commented on docs/CONTRIBUTING.md
> +* Single Responsiblity Principle
Da wäre ein Link auf Wikipedia gut.
https://de.wikipedia.org/wiki/Single-Responsibility-Prinzip

2017-12-05 14:09 UTC, bjoernranft commented on docs/CONTRIBUTING.md
> +* Jede Klasse und Public-Members/Methoden sind zu dokumentieren.
Wo eigentlich dokumentieren? Ist damit ein Kommentar über der methode gemeint? evtl. an http://typedoc.org/ orientieren?

2017-12-05 14:13 UTC, bjoernranft commented on docs/CONTRIBUTING.md
> +* Nur eine Anweisung pro Zeile
bei einzeiligen if-verzweigungen mit oder ohne geschweifte Klammer (ich bin für ohne, aber my 2 cents..) 
if (a < b)
   foo();

oder

if (a < b) {
   foo();
}

2017-12-06 07:52 UTC, sikelerd commented on docs/CONTRIBUTING.md
> +* Nur eine Anweisung pro Zeile
Ich bin eher für die zweite Variante mit geschweiften Klammern

2017-12-06 08:06 UTC, Eymux commented on docs/CONTRIBUTING.md
> +* Nur eine Anweisung pro Zeile
Mit geschweiften Klammern kann man sofort sehen, welche Zeile zum `if` gehört. Ohne die Klammern sorgen falsche Einrückungen leich zu Verwirrungen.

@bjoernranft Die Kommentare auf Github unterstützen übringens Markdown. D.h. man kann Codebeispiele formatieren.

2017-12-06 08:41 UTC, bjoernranft commented on docs/CONTRIBUTING.md
> +* Nur eine Anweisung pro Zeile
@Eymux danke, habe es noch geändert. 

gut, überstimmt, gewöhne ich mich dran. :)

2017-12-06 09:42 UTC, Eymux approved these changes

2017-12-06 09:43 UTC, merged